/* Auto-generated by tools/gen_file_registry.py - do not edit. */

#ifndef FILE_REGISTRY_H
#define FILE_REGISTRY_H

typedef struct {
    const char *path;
    const unsigned char *data;
    unsigned int size;
    unsigned int orig_size;
    unsigned char compressed;
    const char *content_type;
} FileEntry;

extern const FileEntry file_registry[];
extern const unsigned int file_registry_count;

/* Returns a pointer to the entry matching path (e.g. "/index.html"), or NULL. */
const FileEntry *file_registry_find(const char *path);

#endif /* FILE_REGISTRY_H */
