#pragma once

/* Base version of the VoX DoN 3 Host content.
 * Bump this when the host changes — it triggers the app-cache update. */
#define VOXD_VERSION "1.0.0"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/voxd_version.h */
#include "voxd_version.h"

/* Network Settings — port must match the deeplink in assets/param.json */
#define VOXD_PORT 18181

/* Title ID of the installed homescreen app ("VoX DoN 3 Host") */
#define VOXD_TITLE_ID "VOXD00001"

/* Process identity — used to kill stale installer instances on startup */
#define VOXD_THREAD_NAME "voxd.elf"

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"
#define ROUTE_EXIT "/exit"

#include "notification.h"
#include "log.h"