#!/usr/bin/env python3
"""Compute the build version and generate include/voxd_version.h.

Version scheme (mirrors wkali):

    dev:     <base>-dev-<timestamp>
    stable:  <base>
    custom:  <base>-<suffix>

Base version comes from VOXD_VERSION in include/voxd.h. BUILD_TYPE env
(default: dev). CUSTOM_VERSION overrides the suffix and takes precedence.
"""

import datetime
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(REPO, "include", "voxd_version.h")
VOXD_H = os.path.join(REPO, "include", "voxd.h")


def read_base_version():
    try:
        with open(VOXD_H) as f:
            content = f.read()
        m = re.search(r'#define\s+VOXD_VERSION\s+"([^"]+)"', content)
        if m:
            return m.group(1)
    except OSError:
        pass
    return "0.0.0"


def get_version_info(build_type=None):
    if build_type is None:
        build_type = os.environ.get("BUILD_TYPE", "dev")
    base = read_base_version()
    custom = os.environ.get("CUSTOM_VERSION", "").strip()
    timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")

    if custom:
        full = f"{base}-{custom}"
    elif build_type == "stable":
        full = base
    else:
        full = f"{base}-dev-{timestamp}"

    return {
        "full": full,
        "build_time": datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        ),
    }


def header_text(info):
    return (
        "#pragma once\n"
        "/* Auto-generated by tools/gen_version.py - do not edit. */\n"
        "\n"
        f'#define VOXD_FULL_VERSION "{info["full"]}"\n'
        f'#define VOXD_BUILD_TIME "{info["build_time"]}"\n'
    )


def write_if_changed(path, data):
    try:
        with open(path, "rb") as f:
            if f.read() == data:
                return
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    if argv and argv[0] == "--print":
        print(get_version_info()["full"])
        return 0

    info = get_version_info()
    write_if_changed(HEADER, header_text(info).encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())