#!/usr/bin/env python3
"""
Generate a C file registry + cache.appcache manifest from a dist directory.

Scans <dist_dir> recursively and produces:
  - <header_out>  : file_registry.h  (FileEntry struct + extern table)
  - <source_out>  : file_registry.c  (byte arrays + lookup function)
  - <dist_dir>/cache.appcache        (AppCache manifest listing all files)

Usage: gen_file_registry.py <dist_dir> <host_appcache> <header_out> <source_out>
"""

import os
import posixpath
import sys
import zlib

from gen_version import get_version_info

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".htm": "text/html; charset=utf-8",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".ico": "image/x-icon",
    ".appcache": "text/cache-manifest",
    ".txt": "text/plain",
    ".bin": "application/octet-stream",
    ".elf": "application/octet-stream",
}


def detect_content_type(path):
    ext = os.path.splitext(path)[1].lower()
    return CONTENT_TYPES.get(ext, "application/octet-stream")


def include_in_registry(path):
    if "/.git/" in path or path.endswith("/.git"):
        return False
    return True


VERSION_PLACEHOLDER = b"[[VERSION_PLACEHOLDER]]"
BUILD_TIME_PLACEHOLDER = b"[[BUILD_TIME_PLACEHOLDER]]"
APP_DIR_PLACEHOLDER = b"[[APP_DIR_PLACEHOLDER]]"


def apply_version_placeholder(path, data, version, build_time, versioned_paths):
    if path in versioned_paths:
        data = data.replace(VERSION_PLACEHOLDER, version.encode("utf-8"))
        data = data.replace(BUILD_TIME_PLACEHOLDER, build_time.encode("utf-8"))
    return data


def apply_pointer_placeholder(path, data, version):
    if path == "/app/index.html":
        data = data.replace(APP_DIR_PLACEHOLDER, version.encode("utf-8"))
        data = data.replace(VERSION_PLACEHOLDER, version.encode("utf-8"))
    return data


def strip_manifest_attrs(path, data):
    """The VoX-DoN host pages carry `manifest="cache.appcache"` (and poops.html
    `manifest="../cache.appcache"`). Those would make each page a master entry
    of a SECOND cache group and fight the installer page's manifest. Caching is
    the installer page's job (single group) — so strip the attributes from the
    served copies. This is invisible to the user; the pages look/behave the same."""
    if not (path.endswith(".html") or path.endswith(".htm")):
        return data
    data = data.replace(b' manifest="cache.appcache"', b"")
    data = data.replace(b" manifest='cache.appcache'", b"")
    data = data.replace(b' manifest="../cache.appcache"', b"")
    data = data.replace(b" manifest='../cache.appcache'", b"")
    return data


def emit_c_array(out, name, data):
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        out.write(f"    {chunk},\n")
    out.write("};\n")


def compress_entry(data):
    if len(data) < 64:
        return data, False
    co = zlib.compressobj(level=9, wbits=-15)
    comp = co.compress(data) + co.flush()
    if len(comp) >= len(data):
        return data, False
    return comp, True


def read_host_appcache_entries(host_appcache):
    """Read the CACHE section entries from the VoX-DoN host's own
    cache.appcache. They are relative paths (with exact query strings the
    pages request, e.g. slopkit/poops.html?go=... and offsets/9.00.js?v=final).
    Returns a list of absolute URLs (#-comment and empty lines dropped)."""
    entries = []
    if not host_appcache or not os.path.isfile(host_appcache):
        return entries
    in_cache = False
    with open(host_appcache, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line == "CACHE:":
                in_cache = True
                continue
            if line == "NETWORK:":
                in_cache = False
                continue
            if in_cache:
                entries.append("/" + line if not line.startswith("/") else line)
    return entries


def build_manifest(files, version, build_time, app_dir, pointer_path,
                   marker_path, host_entries):
    """Build the AppCache manifest. Ordering matters for partial-cache safety:
    every versioned file is listed first, then the exact query-string URLs the
    host pages request (from the host's own cache.appcache), then the pointer
    page, then the __complete__ marker LAST."""
    lines = [
        "CACHE MANIFEST",
        f"# VoX-DoN-3 Host v{version} (built {build_time}) - "
        "auto-generated by tools/gen_file_registry.py, do not edit.",
        "",
        "CACHE:",
    ]
    cache_entries = [path for path, _ in files if path not in (pointer_path, marker_path)]
    cache_entries.sort()
    lines += cache_entries

    # The poops.html entry in the host cache lists the full query string.
    # Prefix the host-relative entries with the app dir.
    seen = set()
    for entry in sorted(host_entries):
        if entry in seen:
            continue
        seen.add(entry)
        lines.append(app_dir + entry)

    lines.append(pointer_path)
    lines.append(marker_path)
    lines += [
        "",
        "NETWORK:",
        "/install",
        "/version",
        "/exit",
        "",
        "FALLBACK:",
        "/ /index.html",
    ]

    paths = {path for path, _ in files}
    for path in sorted(paths):
        if path == "/index.html" or not path.endswith("/index.html"):
            continue
        directory = os.path.dirname(path)
        if directory != "/":
            lines.append(f"{directory}/ {path}")

    lines += [""]
    return "\n".join(lines)


def main():
    if len(sys.argv) != 5:
        print("Usage: gen_file_registry.py <dist_dir> <host_appcache> <header_out> <source_out>")
        sys.exit(1)

    dist_dir, host_appcache, header_out, source_out = sys.argv[1:5]

    if not os.path.isdir(dist_dir):
        print(f"Error: {dist_dir} not found or not a directory.")
        sys.exit(1)

    version_info = get_version_info()
    version = version_info["full"]
    app_dir = "/app/" + version
    pointer_path = "/app/index.html"
    marker_path = app_dir + "/__complete__"

    marker_full = os.path.join(dist_dir, marker_path.lstrip("/"))
    os.makedirs(os.path.dirname(marker_full), exist_ok=True)
    with open(marker_full, "w", encoding="utf-8") as f:
        f.write(version)

    versioned_paths = ("/index.html", app_dir + "/index.html")

    files = []
    for root, dirs, names in os.walk(dist_dir):
        dirs.sort()
        for name in sorted(names):
            if name == "cache.appcache":
                continue  # regenerated below
            full = os.path.join(root, name)
            rel = os.path.relpath(full, dist_dir).replace(os.sep, "/")
            if not include_in_registry(f"/{rel}"):
                continue
            files.append((f"/{rel}", full))
    files.sort(key=lambda f: f[0])

    host_entries = read_host_appcache_entries(host_appcache)

    manifest_path = os.path.join(dist_dir, "cache.appcache")
    with open(manifest_path, "w") as f:
        f.write(build_manifest(files, version, version_info["build_time"],
                               app_dir, pointer_path, marker_path, host_entries))

    files.append((f"/cache.appcache", manifest_path))
    files.sort(key=lambda f: f[0])

    with open(header_out, "w") as out:
        out.write("/* Auto-generated by tools/gen_file_registry.py - do not edit. */\n")
        out.write("\n")
        out.write("#ifndef FILE_REGISTRY_H\n")
        out.write("#define FILE_REGISTRY_H\n")
        out.write("\n")
        out.write("typedef struct {\n")
        out.write("    const char *path;\n")
        out.write("    const unsigned char *data;\n")
        out.write("    unsigned int size;\n")
        out.write("    unsigned int orig_size;\n")
        out.write("    unsigned char compressed;\n")
        out.write("    const char *content_type;\n")
        out.write("} FileEntry;\n")
        out.write("\n")
        out.write("extern const FileEntry file_registry[];\n")
        out.write("extern const unsigned int file_registry_count;\n")
        out.write("\n")
        out.write("/* Returns a pointer to the entry matching path (e.g. \"/index.html\"), or NULL. */\n")
        out.write("const FileEntry *file_registry_find(const char *path);\n")
        out.write("\n")
        out.write("#endif /* FILE_REGISTRY_H */\n")

    with open(source_out, "w") as out:
        out.write("/* Auto-generated by tools/gen_file_registry.py - do not edit. */\n")
        out.write("\n")
        out.write('#include <string.h>\n')
        out.write("\n")
        out.write('#include "file_registry.h"\n')
        out.write("\n")

        entries = []
        for i, (path, full) in enumerate(files):
            with open(full, "rb") as f:
                data = f.read()
            data = apply_version_placeholder(path, data, version,
                                             version_info["build_time"],
                                             versioned_paths)
            data = apply_pointer_placeholder(path, data, version)
            data = strip_manifest_attrs(path, data)
            stored, compressed = compress_entry(data)
            emit_c_array(out, f"file_{i}", stored)
            out.write("\n")
            entries.append((path, compressed, len(data), len(stored)))

        out.write("const FileEntry file_registry[] = {\n")
        for i, (path, _) in enumerate(files):
            content_type = detect_content_type(path)
            _, compressed, orig_size, stored_size = entries[i]
            out.write(
                f'    {{ "{path}", file_{i}, {stored_size}, {orig_size}, '
                f'{1 if compressed else 0}, "{content_type}" }},\n'
            )
        out.write("};\n")
        out.write("\n")
        out.write("const unsigned int file_registry_count =\n")
        out.write("    sizeof(file_registry) / sizeof(file_registry[0]);\n")
        out.write("\n")
        out.write("const FileEntry *file_registry_find(const char *path) {\n")
        out.write("    if (!path)\n")
        out.write("        return NULL;\n")
        out.write("\n")
        out.write("    for (unsigned int i = 0; i < file_registry_count; i++) {\n")
        out.write('        if (strcmp(file_registry[i].path, path) == 0)\n')
        out.write("            return &file_registry[i];\n")
        out.write("    }\n")
        out.write("\n")
        out.write("    return NULL;\n")
        out.write("}\n")

    print(f"Generated {header_out} and {source_out} ({len(files)} files, {manifest_path})")


if __name__ == "__main__":
    main()